// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'D:/UmiBlog/UmiBlogMain/src/models/admin';
import model_2 from 'D:/UmiBlog/UmiBlogMain/src/models/article';
import model_3 from 'D:/UmiBlog/UmiBlogMain/src/models/user';
import model_4 from 'D:/UmiBlog/UmiBlogMain/src/models/write';

export const models = {
model_1: { namespace: 'admin', model: model_1 },
model_2: { namespace: 'article', model: model_2 },
model_3: { namespace: 'user', model: model_3 },
model_4: { namespace: 'write', model: model_4 },
} as const
