// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
let options = {"masterHistoryType":"browser","base":"/","apps":[{"name":"threeDimensional","entry":"//localhost:8001"},{"name":"websiteAdmin","entry":"//localhost:8002"}]};
export const getMasterOptions = () => options;
export const setMasterOptions = (newOpts) => options = ({ ...options, ...newOpts });
