// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","exact":true,"redirect":"/welcome/","id":"1"},"2":{"path":"/welcome/*","microApp":"threeDimensional","id":"2"},"3":{"path":"/admin/*","microApp":"websiteAdmin","id":"3"},"4":{"path":"/write","id":"4"},"5":{"path":"/write/:key","parentId":"4","id":"5"},"6":{"path":"/drafts","id":"6"},"7":{"path":"/drafts","parentId":"6","id":"7"},"8":{"path":"/","id":"8"},"9":{"path":"/blog","parentId":"8","id":"9"},"10":{"path":"/search","parentId":"8","id":"10"},"11":{"path":"/classes","parentId":"8","id":"11"},"12":{"path":"/tags","parentId":"8","id":"12"},"13":{"path":"/friends","parentId":"8","id":"13"},"14":{"path":"/about","parentId":"8","id":"14"},"15":{"path":"/detail/:articleId","parentId":"8","id":"15"},"16":{"path":"/getList","parentId":"8","id":"16"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(
              () => Promise.resolve((async () => {
          const { getMicroAppRouteComponent } = await import('@@/plugin-qiankun-master/getMicroAppRouteComponent');
          return getMicroAppRouteComponent({ appName: 'threeDimensional', base: '/', routePath: '/welcome/*', masterHistoryType: 'browser', routeProps: {} })
        })()).then(e => e?.default ? e : ({ default: e }))
            ),
'3': React.lazy(
              () => Promise.resolve((async () => {
          const { getMicroAppRouteComponent } = await import('@@/plugin-qiankun-master/getMicroAppRouteComponent');
          return getMicroAppRouteComponent({ appName: 'websiteAdmin', base: '/', routePath: '/admin/*', masterHistoryType: 'browser', routeProps: {} })
        })()).then(e => e?.default ? e : ({ default: e }))
            ),
'4': React.lazy(() => import(/* webpackChunkName: "layouts__BlogLayouts__writePageLayout__index" */'@/layouts/BlogLayouts/writePageLayout/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__write__index" */'@/pages/write/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "layouts__BlogLayouts__writePageLayout__index" */'@/layouts/BlogLayouts/writePageLayout/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__drafts__index" */'@/pages/drafts/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "layouts__BlogLayouts__webPageLayout__index" */'@/layouts/BlogLayouts/webPageLayout/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__blog__index" */'@/pages/blog/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__search__index" */'@/pages/search/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__classes__index" */'@/pages/classes/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__tags__index" */'@/pages/tags/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__friends__index" */'@/pages/friends/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__about__index" */'@/pages/about/index.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__articleDetail__index" */'@/pages/articleDetail/[index].tsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__getList__index" */'@/pages/getList/index.tsx')),
},
  };
}
