// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/didi/UmiBlog/websiteAdmin/src/models/admin';

export const models = {
model_1: { namespace: 'admin', model: model_1 },
} as const
