// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"首页","path":"/home","parentId":"ant-design-pro-layout","id":"2"},"3":{"path":"/admin/categories","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/admin/tags","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/admin/articles","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/admin/comments","parentId":"ant-design-pro-layout","id":"6"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__categories__index" */'@/pages/categories/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__tags__index" */'@/pages/tags/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__articles__index" */'@/pages/articles/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__comments__index" */'@/pages/comments/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/didi/UmiBlog/websiteAdmin/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
